# Generated by Django 2.0.3 on 2018-03-29 14:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('cash_balance', models.IntegerField(default=Decimal('100000'), null=True)),
                ('cash_worth', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('company_code', models.CharField(blank=True, max_length=100, null=True)),
                ('no', models.IntegerField(null=True)),
            ],
        ),
    ]
