# Generated by Django 2.0.3 on 2018-03-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cash_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cash_worth',
            field=models.FloatField(null=True),
        ),
    ]
