# Generated by Django 2.0.3 on 2018-03-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180329_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_company',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_company',
            name='price_per_stock',
            field=models.FloatField(null=True),
        ),
    ]
